#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Mohamed Emad (icon from vnstat-server package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

PLGPATH="/boot/config/plugins/dwdvm"
CONFIG=$PLGPATH/dwdvm.cfg

[ -e "$CONFIG" ] && source $CONFIG

echo ""
echo "Retrieving the network interfaces from the database and the system..."
echo ""

DBLIST="$(vnstat --config /etc/vnstat/vnstat.conf --dbiflist 2>/dev/null)"

if (echo "$DBLIST" | grep "Interfaces in database:" >/dev/null 2>&1); then
    DBLIST="${DBLIST//Interfaces in database: /}"
    DBIFACES=""
    read -r -a DBIFACES <<< "$DBLIST"
    echo "Checking the database's network interfaces against the system's network interfaces..."
    echo ""
    for i in "${DBIFACES[@]}"; do
        if [ ! -e "/sys/class/net/${i}" ]; then
            if [ "$PRIMARY" == "$i" ]; then
                echo "The network interface that you have configured as PRIMARY NETWORK INTERFACE in the GUI is a candidate for removal."
                echo "However as an additional safeguard against unwanted removals the PRIMARY NETWORK INTERFACE was not removed by the script."
                echo "If you really want to remove the PRIMARY NETWORK INTERFACE from the database, please choose another interface in the GUI first."
                echo ""
            else
                vnstat --config /etc/vnstat/vnstat.conf --remove --force "$i" 2>&1
                echo ""
            fi
        fi
    done
    echo "THE OPERATION HAS FINISHED - YOU MAY CLOSE THIS WINDOW NOW."
    echo ""
else
    echo "ERROR RETRIEVING NETWORK INTERFACES FROM BACKEND - PLEASE TRY AGAIN LATER."
    echo ""
fi
