#!/bin/bash

DBLIST="$(vnstat --config /etc/vnstat/vnstat.conf --dbiflist)"
IFLIST="$(vnstat --config /etc/vnstat/vnstat.conf --iflist)"

echo ""
echo "RETRIEVING NETWORK INTERFACES..."
echo ""

if (echo "$DBLIST" | grep "Interfaces in database:" >/dev/null 2>&1) && (echo "$IFLIST" | grep "Available interfaces:" >/dev/null 2>&1); then
    DBLIST="${DBLIST//Interfaces in database: /}"
    DBIFACES=""
    read -r -a DBIFACES <<< "$DBLIST"
    echo "CHECKING NETWORK INTERFACES..."
    echo ""
    for i in "${DBIFACES[@]}"; do
        if ! (echo "$IFLIST" | grep "$i" >/dev/null 2>&1); then
           echo ""
           vnstat --remove --force "$i" 2>&1
           echo ""
        fi
    done
    echo ""
    echo "THE OPERATION HAS FINISHED - YOU MAY CLOSE THIS WINDOW NOW."
else
    echo "ERROR RETRIEVING NETWORK INTERFACES FROM BACKEND - PLEASE TRY AGAIN."
fi
