#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Mohamed Emad (icon from vnstat-server package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

echo ""
echo "###"
echo "### SYSTEM REPORTED AVAILABLE INTERFACES"
echo "###"
echo ""

find /sys/class/net/ 2>&1

echo ""
echo "###"
echo "### BACKEND REPORTED AVAILABLE INTERFACES"
echo "###"
echo ""

vnstat --config /etc/vnstat/vnstat.conf --iflist 2>&1

echo ""
echo "###"
echo "### RECORDED INTERFACES IN THE BACKEND DATABASE"
echo "###"
echo ""

vnstat --config /etc/vnstat/vnstat.conf --dbiflist 2>&1

echo ""
echo "###"
echo "### RUNNING MANUAL CHECK"
echo "###"
echo ""

/usr/sbin/dvm-notify 2>&1
