#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Mohamed Emad (icon from vnstat-client package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
BOOT="/boot/config/plugins/dwdvm"
DOCROOT="/usr/local/emhttp/plugins/dwdvm"

echo "Making sure all existing DVM services are stopped (before config reset)..."
if [ -x /etc/rc.d/rc.vnstat ]; then
    /etc/rc.d/rc.vnstat stop
fi

echo "Deleting existing configuration files and folders..."
rm -f $BOOT/dwdvm.cfg
rm -rf /etc/vnstat
rm -rf $BOOT/vnstat
rm -f /tmp/dvm*notified

echo "Recreating configuration folders..."
if [ ! -d /etc/vnstat ]; then
    mkdir /etc/vnstat
fi

if [ ! -d $BOOT/vnstat ]; then
    mkdir $BOOT/vnstat
fi

echo "Pulling default configuration files from package..."
cp -f $DOCROOT/default.cfg $BOOT/dwdvm.cfg
cp -rf $DOCROOT/vnstat/* $BOOT/vnstat/
cp -rf $BOOT/vnstat/* /etc/vnstat/

echo "Setting up permissions on configuration locations..."
chown root:root /etc/vnstat
chmod 755 /etc/vnstat
chown root:root /etc/vnstat/*
chmod 644 /etc/vnstat/*
chmod 755 /etc/vnstat/dvm-custom-alarms.sh

if [ -x /etc/rc.d/rc.vnstat ]; then
    /etc/rc.d/rc.vnstat write_config 1>/dev/null
fi

echo "DVM configuration is now reset to defaults (database was preserved), reboot or reinstall plugin in case of any problems."
